# Generated by Django 3.0.6 on 2021-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_booked_by', models.CharField(default='', max_length=100)),
                ('slot_time', models.TimeField()),
                ('slot_date', models.DateField()),
                ('slot_booked', models.CharField(default='Not Booked', max_length=15)),
            ],
        ),
    ]
